In [42]:
import sys
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import catboost
import xgboost as xgb
import lightgbm as lgb

In [43]:
pd.set_option('display.max_columns', None)
df = pd.read_csv('data/hakaton.csv', sep=';')
df

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,our_number,ogrn_naprav,name_naprav,ogrn_area,name_area,variant,class,test_date,result
0,МУСЮС,АЛЕКСАНДР,NaN,2013-07-16,М,240045105,АГАФОНОВА,КЛАВДИЯ,NaN,1987-07-06,Ж,106077198701603,26-11-60078-000038-4,1022402487304,муниципальное автономное общеобразовательное у...,1142452001130,краевое бюджетное общеобразовательное учрежден...,20611,6,2026-02-25,Недостаточный
1,СОБОЛЕВ,ЮРИЙ,ГЕННАДЬЕВИЧ,2018-01-26,М,-1236233,КАБЛИН,ВАЛЕНТИН,ГЕННАДИЕВИЧ,1991-03-15,М,1571302,25-11-70122-000036-6,1025007390077,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,1035004258970,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,120126,1,2025-12-16,Недостаточный
2,РЯБОВ,ГЕННАДИЙ,СЕРГЕЕВИЧ,2014-08-21,М,5974549,ЗАКИРОВ,БОРИС,СЕРГЕЕВИЧ,1990-03-07,М,5480835,26-11-70285-000004-4,1037816029393,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ ...,1037816029547,Государственное бюджетное общеобразовательное ...,10410,4,2026-01-20,Достаточный
3,БОРИСОВ,АНАТОЛИЙ,НИКОЛЛАЕВИЧ,2018-07-22,М,3702355,ДЖАЛОЛОВ,ЕВГЕНИЙ,АНДРАНИКОВИЧ,1992-08-23,М,402238324,26-11-70046-000006-7,1021603470360,Муниципальное бюджетное общеобразовательное уч...,1241600037315,Муниципальное бюджетное общеобразовательное уч...,20133,1,2026-02-04,Недостаточный
4,КАРПЕВИЧ,ВИКТОР,ЮРЬЕВИЧ,2019-01-18,М,0000000,ШАПРАН,ЕЛЕНА,ПАВЛОВНА,1995-01-17,Ж,0352905,25-11-60108-000020-9,1023402988234,муниципальное общеобразовательное учреждение С...,1023402982173,"муниципальное общеобразовательное учреждение ""...",60105,1,2025-06-10,достаточный
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25623,ЛАЗАРЕВ,ДЕНИС,ВЛАДИМИРОВИЧ,2015-06-28,М,2118425,ЛАЗАРЕВ,ВАЛЕРИЙ,ПЕТРОВИЧ,1991-10-06,М,402450094,25-11-70289-000015-7,1022701291250,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,60304,3,2025-07-14,Недостаточный
25624,ВИДАКОВ,МИХАИЛ,СЕРГЕЕВИЧ,2018-03-06,М,010080310,КРАСНОКУТСКИЙ,ИЛЬЯ,ВЛАДИМИРОВИЧ,1991-11-07,М,4127610,25-11-70289-000009-8,1022701286508,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,80110,1,2025-08-27,Недостаточный
25625,ТОЛОКОНУШКОВ,ЕВГЕНИЙ,ФЕДОРОВИЧ,2018-04-14,М,-N0849879,ВАСИЛЕНКО,БОРИС,СЕРГЕЕВИЧ,1978-10-02,М,2920197,25-11-70289-000014-8,1022701283208,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,80109,1,2025-08-27,Достаточный
25626,ТИХОНОВ,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,2017-09-11,М,21109201751729,МИРЗОЯН,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,1987-05-17,М,3196439,25-11-70289-000019-9,1022701291250,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,90114,1,2025-09-25,Недостаточный
25627,СОРОКИН,НИКОЛАЙ,НИКОЛАЕВИЧ,2010-01-23,М,8954785,СОРОКИН,ГРИГОРИЙ,ВЛАДИМИРОВИЧ,1978-06-24,М,845120184,25-11-70284-000634-1,1037739385056,Государственное бюджетное общеобразовательное ...,1115074013130,Государственное бюджетное общеобразовательное ...,50802,8,2025-05-07,Недостаточный

In [44]:
df.isna().sum()

last_name               0
first_name              0
middle_name          4469
bdate                   0
gender                  0
id_doc                 33
guard_last_name         0
guard_first_name        0
guard_middle_name    7389
guard_bdate             0
guard_gender            0
guard_id_doc           76
our_number              0
ogrn_naprav             0
name_naprav             0
ogrn_area               0
name_area               0
variant                 0
class                   0
test_date               0
result                  0
dtype: int64

In [45]:
df_without_middle_names = df.drop(['middle_name', 'guard_middle_name'], axis=1)
filtered_df = df_without_middle_names[df_without_middle_names.isna().any(axis=1)]
filtered_df

,last_name,first_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_bdate,guard_gender,guard_id_doc,our_number,ogrn_naprav,name_naprav,ogrn_area,name_area,variant,class,test_date,result
30,СТЕПАНОВ,НИКОЛАЙ,2010-12-29,М,7516029,ШМАРАЕВА,ЕЛЕНА,1988-02-19,Ж,NaN,25-11-60298-000015-0,1027807583132,Государственное бюджетное общеобразовательное ...,1027807574827,Государственное бюджетное общеобразовательное ...,80805,8,2025-08-26,Достаточный
127,ЕФРЕМОВ,ЕВГЕНИЙ,2018-10-17,М,3750502,КОРБУТ,РАИСА,1995-03-26,Ж,NaN,25-11-60298-000044-0,1027807587389,Государственное бюджетное общеобразовательное ...,1027807574827,Государственное бюджетное общеобразовательное ...,90113,1,2025-09-16,Достаточный
133,СЕМИН,АНДРЕЙ,2010-11-30,М,15766731,ТРИХЛЕБ,ВЕРА,1973-08-21,Ж,NaN,25-11-60298-000053-0,1027807573200,Государственное бюджетное общеобразовательное ...,1027807574827,Государственное бюджетное общеобразовательное ...,100807,8,2025-10-07,Достаточный
134,ГОЛУБЕВ,ИВАН,2011-07-04,М,0346248,УХАРСКАЯ,ВАЛЕНТИНА,1985-06-13,Ж,NaN,25-11-60298-000018-8,1187847074843,Государственное бюджетное общеобразовательное ...,1027807574827,Государственное бюджетное общеобразовательное ...,80805,8,2025-08-26,Достаточный
347,КУЗИК,ВЛАДИМИР,2016-05-10,М,NaN,ЧУЛАНОВА,ЛЮДМИЛА,1988-04-30,Ж,6661497,25-11-70147-000011-4,1026102586432,муниципальное общеобразовательное бюджетное уч...,1026102586014,муниципальное автономное общеобразовательное у...,90206,2,2025-09-17,Достаточный
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24773,ТРОФИМОВ,ФЕДОР,2016-02-22,М,107144,ТРОФИМОВ,ВЛАДИМИР,1973-06-07,М,NaN,25-11-60298-000038-6,1027807585948,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ ...,1027807574827,Государственное бюджетное общеобразовательное ...,90306,3,2025-09-09,Достаточный
24796,БАТЕЕВ,ВЛАДИМИР,2018-07-03,М,405486926,БАТЕЕВ,АЛЕКСЕЙ,1991-05-13,М,NaN,25-11-60298-000011-6,1027807586113,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ ...,1027807574827,Государственное бюджетное общеобразовательное ...,80110,1,2025-08-19,Достаточный
24963,ШИРОБОКОВ,СЕРГЕЙ,2018-10-03,М,3787117,ШИРОБОКОВ,НИКОЛАЙ,1991-06-20,М,NaN,25-11-60298-000016-9,1027807588082,Государственное бюджетное общеобразовательное ...,1027807574827,Государственное бюджетное общеобразовательное ...,80110,1,2025-08-26,Достаточный
25257,ФАТТАХЕТДИНОВ,АЛЕКСАНДР,2015-03-27,М,44116309,СТАРОДУБЦЕВА,ИРИНА,1978-06-20,Ж,NaN,25-11-60298-000043-3,1027807585300,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ ...,1027807574827,Государственное бюджетное общеобразовательное ...,90113,1,2025-09-09,Достаточный
25258,ГУЩИН,ЮЛИЙ,2013-03-20,М,-1261045,САЗОНОВА,НИНА,1991-04-04,Ж,NaN,25-11-60298-000020-9,1027807585300,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ ...,1027807574827,Государственное бюджетное общеобразовательное ...,80705,7,2025-08-26,Достаточный

In [46]:
num_of_child_ids = len(df['id_doc'].unique())
num_of_child_ids

21928

In [69]:
result = df.groupby(['id_doc']).size().reset_index(name='count').sort_values('count', ascending=False)
result

            id_doc  count
0                -     13
6470       0594160      9
13054    404331516      8
6844       0682253      8
13567    404832737      6
...            ...    ...
21911     №9870188      1
4      --406127589      1
3      --406034086      1
2      --404622851      1
1      --404577571      1

[21927 rows x 2 columns]

In [47]:
result = df.groupby(['first_name', 'middle_name', 'last_name', 'id_doc']).size().reset_index(name='count').sort_values('count', ascending=False)
result

      first_name    middle_name  last_name     id_doc  count
13992       НИНА    ПРОКОФЬЕВНА     ЛАРИНА  404832737      6
15953     СЕРГЕЙ     ВАСИЛЬЕВИЧ     СИЛАЕВ    0466996      6
8454       ЕЛЕНА    ПРОКОФЬЕВНА     ЛАРИНА  406037397      5
4234        ВЕРА  АЛЕКСАНДРОВНА    ПРИДИНА  404331516      5
12524    НАДЕЖДА     ВАСИЛЬЕВНА  РАТНИКОВА  N16691028      5
...          ...            ...        ...        ...    ...
26     АЛЕКСАНДР  АЛЕКСАНДРОВИЧ    ВАРСЕЕВ    5462291      1
1333     АЛЕКСЕЙ   ВЛАДИМИРОВИЧ   ДЖАЛОЛОВ   -5002448      1
28     АЛЕКСАНДР  АЛЕКСАНДРОВИЧ     ВЛАСОВ    7145103      1
29     АЛЕКСАНДР  АЛЕКСАНДРОВИЧ  ВОЛЧЕНКОВ    3263210      1
13     АЛЕКСАНДР  АЛЕКСАНДРОВИЧ    АРХИПОВ    0333584      1

[18479 rows x 5 columns]

In [68]:
result = df.groupby(['test_date', 'id_doc']).size().reset_index(name='count').sort_values('count', ascending=False)
result

        test_date      id_doc  count
7449   2025-08-27   404331516      8
9019   2025-09-04     -767625      5
15023  2025-10-09    05352839      4
13992  2025-09-30    18240062      4
15015  2025-10-09    05019385      4
...           ...         ...    ...
17     2025-04-22      964524      1
18     2025-04-23  -N№0049176      1
19     2025-04-23     0698803      1
20     2025-04-23     6194544      1
21     2025-04-23    №0413789      1

[25174 rows x 3 columns]

In [48]:
result = df.groupby('test_date').size().reset_index(name='count').sort_values('count',ascending=False)
result

      test_date  count
106  2025-08-27   1005
100  2025-08-20    749
123  2025-09-17    620
105  2025-08-26    570
122  2025-09-16    536
..          ...    ...
29   2025-05-23      1
31   2025-05-25      1
240  2026-02-09      1
1    2025-04-06      1
0    2025-04-03      1

[267 rows x 2 columns]

In [53]:
result['test_date'] = pd.to_datetime(result['test_date'])

In [71]:
num_of_our_number = len(df['our_number'].unique())
num_of_our_number

25628

In [65]:
df_sorted_mixed = df.sort_values(by=['id_doc', 'test_date'], ascending=[True, False])
df_sorted_mixed.head(50)

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,our_number,ogrn_naprav,name_naprav,ogrn_area,name_area,variant,class,test_date,result
24268,ФРОЛОВСКИЙ,ВАЛЕНТИН,СЕРАФИМОВИЧ,2018-05-24,М,-,АНТИПОВА,ЕКАТЕРИНА,ВИКТОРОВНА,1994-07-14,Ж,0505404,26-11-30661-000003-2,1025003082147,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,1035001604340,МУНИЦИПАЛЬНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ И...,20134,1,2026-02-17,достаточный
4179,КЛИМОВ,ДЕНИС,СЕРГЕЕВИЧ,2011-11-29,М,-,ЮН,МАКСИМ,ВЛАДИМИРОВИЧ,1989-11-15,М,6761430,26-11-30858-000004-9,1026500527580,Муниципальное автономное общеобразовательное у...,1026500529769,Муниципальное автономное общеобразовательное у...,10810,8,2026-01-22,недостаточный
15040,ЕРМОШКИН,АЛЕКСАНДР,NaN,2018-09-20,М,-,ПАТЯК,АЛЛА,NaN,1990-02-16,Ж,2211155,25-11-50141-000032-6,1035011300862,Муниципальное общеобразовательное учреждение Д...,1035007003030,МУНИЦИПАЛЬНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ С...,120126,1,2025-12-23,Недостаточный
13370,ШЕВЧЕНКО,АНАТОЛИЙ,СЕРГЕЕВИЧ,2018-07-22,М,-,ШЕВЧЕНКО,ВИКТОР,МИХАЙЛОВИЧ,1986-11-07,М,0469438,25-11-60137-000081-8,1215000077170,Муниципальное общеобразовательное учреждениеср...,1035005006772,МУНИЦИПАЛЬНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ Г...,120125,1,2025-12-09,Достаточный
17852,МИХАЙЛОВСКИЙ,АЛЕКСАНДР,АНАТОЛЬЕВИЧ,2018-10-04,М,-,ВИХРОВА,ЗИНАИДА,ИВАНОВНА,1991-02-19,Ж,0249074,25-11-70284-000555-3,1127747074751,Государственное бюджетное общеобразовательное ...,1115074013130,Государственное бюджетное общеобразовательное ...,110121,1,2025-11-26,Недостаточный
17755,ПЕТРОВ,АЛЕКСАНДР,АЛЕКСЕЕВИЧ,2011-11-02,М,-,НИКИФОРОВА,ЛЮБОВЬ,ИВАНОВНА,1975-08-26,Ж,403025385,25-11-70112-000050-8,1024001339185,муниципальное бюджетное общеобразовательное уч...,1024001186550,муниципальное бюджетное общеобразовательное уч...,100807,8,2025-10-28,Недостаточный
850,НЕВЕЧЕРЯ,ВИКТОР,МИХАЙЛОВИЧ,2019-02-19,М,-,МЕДВЕДЕВА,НАДЕЖДА,БОРИСОВНА,1992-07-08,Ж,406014854,25-11-70289-000018-5,1022701284693,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,90113,1,2025-09-18,Недостаточный
11808,ИГНАТОВА,ОЛЬГА,СЕРГЕЕВНА,2018-03-05,Ж,-,ИГНАТОВА,ЕЛЕНА,БОРИСОВНА,1986-03-21,Ж,6013400071,25-11-70147-000009-1,1026102587169,муниципальное общеобразовательное бюджетное уч...,1026102586014,муниципальное автономное общеобразовательное у...,90113,1,2025-09-17,Достаточный
5948,МИЗАЙЛОВА,ЕКАТЕРИНА,МИХАЙЛОВНА,2017-03-25,Ж,-,СЕЛЕЗНЕВ,АЛЕКСАНДР,АЛЕКСЕЕВИЧ,1987-01-20,М,401915295,25-11-10701-000053-7,1024840850286,муниципальное бюджетное общеобразовательное уч...,1194827011081,муниципальное автономное общеобразовательное у...,80110,1,2025-09-02,Недостаточный
24656,ПЛАТОНОВ,АЛЕКСЕЙ,ВЛАДИМИРОВИЧ,2017-12-23,М,-,ГОЛУБКОВА,ОЛЬГА,МИХАЙЛОВНА,1995-06-23,Ж,0740204,25-11-40641-000105-8,1022501295409,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,1022501305804,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,80205,2,2025-08-27,Недостаточный
10516,СТАРШОВА,ОЛЬГА,АЛЕКСАНДРОВНА,2018-01-30,Ж,-,СТАРШОВА,ИРИНА,ВЛАДИМИРОВНА,1988-03-17,Ж,6451152,25-11-60108-000018-8,1023402988234,муниципальное общеобразовательное учреждение С...,1023402982173,"муниципальное общеобразовательное учреждение ""...",80110,1,2025-08-26,достаточный
17914,МАЛКОВ,РОМАН,ИАНОВИЧ,2014-12-17,М,-,ПАНОВА,ЛИДИЯ,ФАЗЫЛОВНА,1981-12-01,Ж,-,25-11-10701-000036-5,1024800833628,муниципальное бюджетное общеобразовательное уч...,1194827011081,муниципальное автономное общеобразовательное у...,80505,5,2025-08-19,Недостаточный
1393,САНТАЛОВ,НИКОЛАЙ,ЕФИМОВИЧ,2012-03-08,М,-,САНТАЛОВ,РОМАН,NaN,1987-01-18,М,-,25-11-40631-000029-3,1022302831902,Муниципальное общеобразовательное бюджетное уч...,1032311676990,Муниципальное общеобразовательное бюджетное уч...,40701,7,2025-04-30,Недостаточный
6406,ЯНИНА,ЛИДИЯ,ЕВГЕНЬЕВНА,2013-10-11,Ж,--404577571,ПОНОМАРЕНКО,АЛЕКСАНДР,ВИКТОРОВИЧ,1990-09-06,М,5022469280,25-11-20681-000016-0,1025602002524,Муниципальное общеобразовательное автономное у...,1045610200998,Муниципальное общеобразовательное автономное у...,90606,6,2025-10-02,Недостаточный
6408,ЯНИНА,ОКСАНА,ЕВГЕНЬЕВНА,2017-05-01,Ж,--404622851,ПОНОМАРЕНКО,АЛЕКСАНДР,ВИКТОРОВИЧ,1990-09-06,М,5022469280,25-11-20681-000015-2,1025602002524,Муниципальное общеобразовательное автономное у...,1045610200998,Муниципальное общеобразовательное автономное у...,90206,2,2025-10-02,Недостаточный
21397,СОРОКИНА,МАРИЯ,РУСТАМОВНА,2018-08-21,Ж,--406034086,СОРОКИНА,ВАЛЕНТИНА,СТЕПАНОВНА,1990-12-09,Ж,--405544902,25-11-50050-000003-9,1021603629299,Муниципальное бюджетное общеобразовательное уч...,1241600037755,Муниципальное бюджетное общеобразовательное уч...,60107,1,2025-07-30,ДОСТАТОЧНЫЙ
15656,ВИЦКЕ,АЛЕКСАНДР,АЛЕКСЕЕВИЧ,2013-08-22,М,--406127589,ЧУДИНОВА,ЖАННА,ЮРЬЕВНА,1964-02-23,Ж,5309820113,25-11-20681-000017-1,1025602002524,Муниципальное общеобразовательное автономное у...,1045610200998,Муниципальное общеобразовательное автономное у...,90606,6,2025-10-02,Недостаточный
2455,ЖЕЛЕЗНЯК,ВАСИЛИЙ,АНАТОЛЬЕВИЧ,2017-10-03,М,--577057,ЖЕЛЕЗНЯК,СУРИК,ЮРЬЕВИЧ,1979-09-03,М,404449790,25-11-70284-000323-6,1127747074751,Государственное бюджетное общеобразовательное ...,1115074013130,Государственное бюджетное общеобразовательное ...,50104,1,2025-06-04,Недостаточный
10892,ВАСУДАРОВА,ЕВДОКИЯ,ВИТАЛЬЕВНА,2019-01-02,Ж,--678843,ВАСУДАРОВА,ИРИНА,ИВАНОВНА,1988-07-23,Ж,03998701,25-11-60307-000003-9,1022700650708,Муниципальное бюджетное общеобразовательное уч...,1022700521326,Муниципальное общеобразовательное учреждение с...,100117,1,2025-10-09,Достаточный
24285,ШУРТАНОВ,ВИКТОР,НИКОЛАЕВИЧ,2018-03-19,М,--698697,ВАЛЬКОВСКАЯ,РИММА,ВАСИЛЬЕВНА,1992-02-12,Ж,03572626,25-11-40856-000008-1,1027101415395,Муниципальное бюджетное общеобразовательное уч...,1027101414053,Муниципальное бюджетное общеобразовательное уч...,80110,1,2025-08-25,Достаточный
19904,ГОЛИКОВА,СОФЬЯ,ЮРЬЕВНА,2010-02-10,Ж,--713179,ШУСТОВА,ИРИНА,АЛЕКСЕЕВНА,1985-12-29,Ж,402792353,25-11-50050-000051-1,1021603629299,Муниципальное бюджетное общеобразовательное уч...,1241600037755,Муниципальное бюджетное общеобразовательное уч...,90906,9,2025-09-24,ДОСТАТОЧНЫЙ
4615,СИДОРЕНОК,ЮРИЙ,АЛЕКСАНДРОВИЧ,2018-03-08,М,--№541283,СИДОРЕНОК,САИТ,ИЛЬИЧ,1980-03-12,М,02391568,25-11-50265-000151-4,1026605616586,Муниципальное автономное общеобразовательное у...,1026604949326,Муниципальное бюджетное общеобразовательное уч...,90113,1,2025-09-20,Достаточный
18865,КУЗЬМИНА,КЛАВДИЯ,ВИКТОРОВНА,2018-09-28,Ж,--№782397,ЮСУПОВ,ВАЛЕРИЙ,ИВАНОВИЧ,1981-12-05,М,82№1655683,25-11-20579-000031-8,1021603275704,Муниципальное бюджетное общеобразовательное уч...,1021603273009,Муниципальное бюджетное общеобразовательное уч...,90113,1,2025-08-27,Достаточный
21758,КУЗЬМИНА,КЛАВДИЯ,ВИКТОРОВНА,2018-09-28,Ж,--№782397,ЮСУПОВ,ВАЛЕРИЙ,ИВАНОВИЧ,1981-12-05,М,82№1655683,25-11-20579-000013-6,1021603275704,Муниципальное бюджетное общеобразовательное уч...,1021603273009,Муниципальное бюджетное общеобразовательное уч...,90113,1,2025-08-27,Достаточный
22527,ПОНОМАРЕВ,ВИКТОР,ВАСИЛЬЕВИЧ,2018-11-14,М,--№787914,КОВАЛЕНКО,СВЕТЛАНА,ПЕТРОВНА,1994-03-26,Ж,1041839,25-11-20579-000008-7,1021603275704,Муниципальное бюджетное общеобразовательное уч...,1021603273009,Муниципальное бюджетное общеобразовательное уч...,90113,1,2025-08-27,Достаточный
22602,ПОНОМАРЕВ,ВИКТОР,ВАСИЛЬЕВИЧ,2018-11-14,М,--№787914,КОВАЛЕНКО,СВЕТЛАНА,ПЕТРОВНА,1994-03-26,Ж,1041839,25-11-20579-000026-8,1021603275704,Муниципальное бюджетное общеобразовательное уч...,1021603273009,Муниципальное бюджетное общеобразовательное уч...,90113,1,2025-08-27,Достаточный
10144,РЯБОВА,ОЛЬГА,ТИТОВНА,2017-07-21,Ж,--№870882,МАЗИКОВА,СВЕТЛАНА,NaN,1991-07-02,Ж,0907881,25-11-50265-000162-5,1026605614452,Муниципальное автономное общеобразовательное у...,1026604949326,Муниципальное бюджетное общеобразовательное уч...,90206,2,2025-09-20,Недостаточный
980,КОЛЕСОВ,БОРИС,ВЛАДИМИРОВИЧ,2018-02-21,М,-0004158,СЕМКИНА,ТАТЬЯНА,NaN,1984-12-15,Ж,1889797,25-11-70122-000003-4,1035004258948,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,1035004258970,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,80111,1,2025-08-26,недостаточный
11756,ПАХОЛКОВА,НИНА,НИКОЛАЕВНА,2013-10-06,Ж,-0010126,ЛИТВИНОВА,КЛАВДИЯ,ФЕДОРОВНА,1986-07-29,Ж,9701256,25-11-70041-000004-9,1031616005101,муниципальное бюджетное общеобразовательное уч...,1231600036854,Муниципальное бюджетное общеобразовательное уч...,606,6,2025-09-05,Достаточный
12410,ПАНИНА,МАРИЯ,ГРИГОРЬЕВНА,2016-08-01,Ж,-0010778,МАКАРОВА,НАТАЛИЯ,ИВАНОВНА,1966-02-22,Ж,4620977117,25-11-70122-000027-1,1025007390077,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,1035004258970,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,110121,1,2025-11-11,Достаточный
14226,ПОЛИЦИН,НИКОЛАЙ,МИХАЙЛОВИЧ,2017-08-01,М,-001205,ХАЧАТУРЯН,НАДЕЖДА,НИКОЛАЕВНА,1990-09-27,Ж,03619303,25-11-70242-000077-0,1036405201205,Муниципальное автономное общеобразовательное у...,1206400004470,муниципальное автономное общеобразовательное у...,100207,2,2025-10-22,Недостаточный
22042,ВАСЕНИНА,ИРИНА,ИВАНОВНА,2015-09-04,Ж,-0016088,НОВИЧКОВ,ПАНТЕЛЕЙ,НИКОЛАЕВИЧ,1985-04-02,М,521931629,26-11-60080-000014-2,1022502130419,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,1022501912564,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,20411,4,2026-02-25,Недостаточный
12290,ДРАНКО,ЛИДИЯ,ВАСИЛЬЕВНА,2017-08-26,Ж,-002133,СМИРНОВА,ОЛЬГА,ВЛАДИМИРОВНА,1995-05-31,Ж,05581961,25-11-70019-000001-5,1020502307132,Муниципальное казенное общеобразовательное учр...,1080547000060,МУНИЦИПАЛЬНОЕ КАЗЕННОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧР...,120309,3,2025-12-11,Достаточный
21266,ЕЛИСЕЕВА,ТАТЬЯНА,ВИКТОРОВНА,2018-12-31,Ж,-0030371,ЕЛИСЕЕВА,ГАЛИНА,ВЛАДИМИРОВНА,1989-01-18,Ж,0242393,25-11-40676-000016-2,1024001430320,муниципальное бюджетное общеобразовательное уч...,1024001435490,муниципальное бюджетное общеобразовательное у...,90114,1,2025-09-06,Достаточный
11980,ЧЕРКАСОВА,ЕЛЕНА,ФРОЛОВНА,2018-05-29,Ж,-0036116,ИРКОВ,АНАТОЛИЙ,ИВАНОВИЧ,1991-11-05,М,5303482,25-11-70284-000471-7,1027739639938,Государственное бюджетное общеобразовательное ...,1115074013130,Государственное бюджетное общеобразовательное ...,90113,1,2025-10-01,Недостаточный
14258,ШЛЫХАНО,СЕРГЕЙ,СЕМЕНОВИЧ,2018-11-17,М,-0071728,ПАНИБРАТОВА,ГАЛИНА,NaN,1990-08-21,Ж,4119313,25-11-70289-000021-3,1022701284693,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,80110,1,2025-08-15,Недостаточный
9787,БАЙКОВА,ЕВГЕНИЯ,ЗАХАРОВНА,2018-07-12,Ж,-01018216,КИРЯКИНА,МАРГАРИТА,NaN,1994-11-10,Ж,3775697,25-11-50050-000025-7,1021603629299,Муниципальное бюджетное общеобразовательное уч...,1241600037755,Муниципальное бюджетное общеобразовательное уч...,80109,1,2025-08-27,ДОСТАТОЧНЫЙ
22000,ПОДГУЗОВ,РОМАН,ИГОРЕВИЧ,2011-07-27,М,-0114705,КОРОТКОВА,НИНА,КОНСТАНТИНОВНА,1989-06-11,Ж,8885871,25-11-70284-000676-2,1147746413022,Государственное бюджетное общеобразовательное ...,1115074013130,Государственное бюджетное общеобразовательное ...,10810,8,2026-01-28,Недостаточный
24114,БОЛТАЕВ,СЕРГЕЙ,МИХАЙЛОВИЧ,2017-09-16,М,-011843,ПЫЛЬЦЫНА,ГАЛИНА,МИХАЙЛОВНА,1991-08-10,Ж,4523726527,25-11-30659-000085-1,1035002452583,муниципальное бюджетное общеобразовательное уч...,1145012004191,МУНИЦИПАЛЬНОЕ АВТОНОМНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ У...,120209,2,2025-12-09,Недостаточный
23412,КАМАНИН,АЛЕКСЕЙ,NaN,2011-01-25,М,-0123045,КАМАНИН,МАНСУР,NaN,1989-01-21,М,1407373,25-11-70284-000595-7,1027739374772,Государственное бюджетное общеобразовательное ...,1115074013130,Государственное бюджетное общеобразовательное ...,80905,9,2025-08-25,Недостаточный
6746,БЕЛОВА,ВАЛЕНТИНА,ВАЛЕРЬЕВНА,2018-10-08,Ж,-01298278,МАТУШКИН,ИГОРЬ,ПАВЛОВИЧ,1988-07-12,М,0209691,25-11-20654-000239-9,1033801540167,Муниципальное общеобразовательное учреждение И...,1023801537880,Государственное нетиповое общеобразовательное ...,50103,1,2025-05-17,Достаточный
702,ХУДАЙБЕРГЕНОВ,АЛЕКСЕЙ,NaN,2010-02-23,М,-0130318,САВАТЕЕВА,МАРИНА,NaN,1987-04-08,Ж,1044647,25-11-70284-000599-9,1137746787551,Государственное бюджетное общеобразовательное ...,1115074013130,Государственное бюджетное общеобразовательное ...,80905,9,2025-08-25,Недостаточный
24213,ДВОРНИКОВ,ГЕННАДИЙ,АЛЕКСЕЕВИЧ,2010-11-13,М,-0134498,ТИРЮТКИНА,ВЕРА,АЛЕКСАНДРОВНА,1982-10-12,Ж,9598041,25-11-30810-000015-0,1027103071335,Муниципальное бюджетное общеобразовательное уч...,1027103070983,Муниципальное бюджетное общеобразовательное уч...,110908,9,2025-11-19,Достаточный
221,ХАРИТОНОВ,СЕРГЕЙ,NaN,2012-04-26,М,-0136479,ГАССИЕВА,ИРИНА,NaN,1994-03-12,Ж,1241409,25-11-60122-000087-9,1024000535360,"муниципальное общеобразовательное учреждение ""...",1024000535305,"Муниципальное общеобразовательное учреждение ""...",120709,7,2025-12-09,Недостаточный
110,ХАРИТОНОВ,СЕРГЕЙ,NaN,2012-04-26,М,-0136479,ГАССИЕВА,ИРИНА,NaN,1994-03-12,Ж,1241409,25-11-60122-000055-3,1024000535360,"муниципальное общеобразовательное учреждение ""...",1024000535305,"Муниципальное общеобразовательное учреждение ""...",90706,7,2025-09-06,недостаточный
25307,КУЗЕНКОВ,АЛЕКСАНДР,МАГОМЕДОВИЧ,2011-01-03,М,-0136944,ЛИТВИНОВА,КЛАВДИЯ,ФЕДОРОВНА,1986-07-29,Ж,9701256,25-11-70041-000002-5,1031616005101,муниципальное бюджетное общеобразовательное уч...,1231600036854,Муниципальное бюджетное общеобразовательное уч...,806,8,2025-09-05,Достаточный
14868,КУЛИШ,НИКОЛАЙ,NaN,2012-11-01,М,-0137406,АЛЕЕВА,ЕЛЕНА,NaN,1988-11-20,Ж,831190101,25-11-40692-000042-3,1035007005076,МУНИЦИПАЛЬНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧРЕЖДЕНИЕ С...,1145009017680,Муниципальное автономное общеобразовательное у...,110508,5,2025-11-18,Недостаточный
15800,БОРИСОВ,СЕРГЕЙ,АЛЕКСАНДРОВИЧ,2018-05-01,М,-0143686,КОЗИНА,ЮЛИЯ,АЛЕКСЕЕВНА,1995-04-21,Ж,2597857,25-11-30603-000011-3,1022304060690,Муниципальное бюджетное общеобразовательное уч...,1022304060767,Муниципальное бюджетное общеобразовательное уч...,120126,1,2025-12-17,Достаточный
18723,ХАРИТОНЕНКОВА,ТАТЬЯНА,АЛЕКСЕЕВНА,2008-07-07,Ж,-0152347,ШАРОВ,ВЯЧЕСЛАВ,САИДГУРБАН ОГЛЫ,1982-02-08,М,98083,25-11-10839-000031-3,1026605244984,Муниципальное автономное общеобразовательное у...,1026605763645,Муниципальное автономное общеобразовательное у...,81105,11,2025-08-22,Недостаточный
16761,ИСМАТОВ,ВАЛЕРИЙ,ВЛАДИМИРОВИЧ,2013-01-08,М,-016701,ПОЛЕЩУК,ЕЛЕНА,ИВАНОВНА,1983-10-01,Ж,5416283,25-11-50255-000004-3,1026500917079,Муниципальное бюджетное общеобразовательное уч...,1026500914725,Муниципальное бюджетное общеобразовательное уч...,80605,6,2025-08-28,Достаточный