In [2]:
import sys
import pandas as pd
import numpy as np
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
pd.set_option('display.max_columns', None)
df = pd.read_csv('data/hakaton.csv', sep=';')
df

,last_name,first_name,middle_name,bdate,gender,id_doc,guard_last_name,guard_first_name,guard_middle_name,guard_bdate,guard_gender,guard_id_doc,our_number,ogrn_naprav,name_naprav,ogrn_area,name_area,variant,class,test_date,result
0,МУСЮС,АЛЕКСАНДР,NaN,2013-07-16,М,240045105,АГАФОНОВА,КЛАВДИЯ,NaN,1987-07-06,Ж,106077198701603,26-11-60078-000038-4,1022402487304,муниципальное автономное общеобразовательное у...,1142452001130,краевое бюджетное общеобразовательное учрежден...,20611,6,2026-02-25,Недостаточный
1,СОБОЛЕВ,ЮРИЙ,ГЕННАДЬЕВИЧ,2018-01-26,М,-1236233,КАБЛИН,ВАЛЕНТИН,ГЕННАДИЕВИЧ,1991-03-15,М,1571302,25-11-70122-000036-6,1025007390077,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,1035004258970,МУНИЦИПАЛЬНОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ УЧ...,120126,1,2025-12-16,Недостаточный
2,РЯБОВ,ГЕННАДИЙ,СЕРГЕЕВИЧ,2014-08-21,М,5974549,ЗАКИРОВ,БОРИС,СЕРГЕЕВИЧ,1990-03-07,М,5480835,26-11-70285-000004-4,1037816029393,ГОСУДАРСТВЕННОЕ БЮДЖЕТНОЕ ОБЩЕОБРАЗОВАТЕЛЬНОЕ ...,1037816029547,Государственное бюджетное общеобразовательное ...,10410,4,2026-01-20,Достаточный
3,БОРИСОВ,АНАТОЛИЙ,НИКОЛЛАЕВИЧ,2018-07-22,М,3702355,ДЖАЛОЛОВ,ЕВГЕНИЙ,АНДРАНИКОВИЧ,1992-08-23,М,402238324,26-11-70046-000006-7,1021603470360,Муниципальное бюджетное общеобразовательное уч...,1241600037315,Муниципальное бюджетное общеобразовательное уч...,20133,1,2026-02-04,Недостаточный
4,КАРПЕВИЧ,ВИКТОР,ЮРЬЕВИЧ,2019-01-18,М,0000000,ШАПРАН,ЕЛЕНА,ПАВЛОВНА,1995-01-17,Ж,0352905,25-11-60108-000020-9,1023402988234,муниципальное общеобразовательное учреждение С...,1023402982173,"муниципальное общеобразовательное учреждение ""...",60105,1,2025-06-10,достаточный
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25623,ЛАЗАРЕВ,ДЕНИС,ВЛАДИМИРОВИЧ,2015-06-28,М,2118425,ЛАЗАРЕВ,ВАЛЕРИЙ,ПЕТРОВИЧ,1991-10-06,М,402450094,25-11-70289-000015-7,1022701291250,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,60304,3,2025-07-14,Недостаточный
25624,ВИДАКОВ,МИХАИЛ,СЕРГЕЕВИЧ,2018-03-06,М,010080310,КРАСНОКУТСКИЙ,ИЛЬЯ,ВЛАДИМИРОВИЧ,1991-11-07,М,4127610,25-11-70289-000009-8,1022701286508,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,80110,1,2025-08-27,Недостаточный
25625,ТОЛОКОНУШКОВ,ЕВГЕНИЙ,ФЕДОРОВИЧ,2018-04-14,М,-N0849879,ВАСИЛЕНКО,БОРИС,СЕРГЕЕВИЧ,1978-10-02,М,2920197,25-11-70289-000014-8,1022701283208,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,80109,1,2025-08-27,Достаточный
25626,ТИХОНОВ,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,2017-09-11,М,21109201751729,МИРЗОЯН,ВЛАДИМИР,АЛЕКСАНДРОВИЧ,1987-05-17,М,3196439,25-11-70289-000019-9,1022701291250,муниципальное автономное общеобразовательное у...,1022701289170,муниципальное бюджетное общеобразовательное уч...,90114,1,2025-09-25,Недостаточный
25627,СОРОКИН,НИКОЛАЙ,НИКОЛАЕВИЧ,2010-01-23,М,8954785,СОРОКИН,ГРИГОРИЙ,ВЛАДИМИРОВИЧ,1978-06-24,М,845120184,25-11-70284-000634-1,1037739385056,Государственное бюджетное общеобразовательное ...,1115074013130,Государственное бюджетное общеобразовательное ...,50802,8,2025-05-07,Недостаточный

In [4]:
df.isna().sum()

last_name               0
first_name              0
middle_name          4469
bdate                   0
gender                  0
id_doc                 33
guard_last_name         0
guard_first_name        0
guard_middle_name    7389
guard_bdate             0
guard_gender            0
guard_id_doc           76
our_number              0
ogrn_naprav             0
name_naprav             0
ogrn_area               0
name_area               0
variant                 0
class                   0
test_date               0
result                  0
dtype: int64

In [12]:
df.describe()

        ogrn_naprav     ogrn_area
count  2.562800e+04  2.562800e+04
mean   1.104995e+12  1.050151e+12
std    2.044263e+12  5.329155e+10
min    1.020101e+12  1.020101e+12
25%    1.024701e+12  1.025203e+12
50%    1.027102e+12  1.027403e+12
75%    1.035006e+12  1.035404e+12
max    3.210571e+14  1.241600e+12

In [13]:
num_of_child_ids = len(df['id_doc'].unique())
num_of_child_ids

21928

In [11]:
id_loc_num = df.groupby('id_doc').size().reset_index(name='count').sort_values('count',ascending=False)
id_loc_num

            id_doc  count
0                -     13
6470       0594160      9
13054    404331516      8
6844       0682253      8
13567    404832737      6
...            ...    ...
21911     №9870188      1
4      --406127589      1
3      --406034086      1
2      --404622851      1
1      --404577571      1

[21927 rows x 2 columns]

In [25]:
id_neg = id_loc_num['id_doc'].str.isdigit().sum()
id_neg

np.int64(15382)

## ПЕРЕЙДЕМ К АНАЛИТИКЕ ID ОПЕКУНА

In [29]:
num_of_guard_ids = len(df['guard_id_doc'].unique())
num_of_guard_ids

18125

In [30]:
id_loc_num = df.groupby('guard_id_doc').size().reset_index(name='count').sort_values('count',ascending=False)
id_loc_num

      guard_id_doc  count
2485       0682318     60
15259  8522№608090     12
13406   6824328757     11
10174    405073438     11
13763   7514515713     10
...            ...    ...
18112    №N4545127      1
18113    №N4571564      1
18114    №N4588721      1
18115    №N4602165      1
18116    №N4631168      1

[18124 rows x 2 columns]

In [31]:
id_incorrect = id_loc_num['guard_id_doc'].str.isdigit().sum()
id_neg

np.int64(15382)

## 3.попробуем убрать